[tool.poetry]
name = "jetton-check"
version = "0.1.0"
description = ""
authors = ["Mykyta Prokaiev <mykytaprokaiev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
httpx = "^0.27.0"
pydantic = "2.5.0"
argparse = "^1.4.0"
tqdm = "^4.66.2"
python-dotenv = "^1.0.1"
schedule = "^1.2.1"
aiogram = "^3.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
